name: lakasir
description: A new Flutter project.
publish_to: 'none'
version: 0.0.21

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.1.0
  infinite_scroll_pagination: ^5.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^5.0.2
  get: ^4.6.6
  image_cropper: ^9.1.0
  http_parser: ^4.0.2
  flutter_masked_text2: ^0.9.1
  heroicons: ^0.11.0
  pdf: ^3.10.7
  google_fonts: ^6.1.0
  flutter_pdfview: ^1.3.2
  blue_thermal_printer:
    git:
      url: https://github.com/hazbu/blue_thermal_printer
      ref: master
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  image: ^4.1.7
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  screenshot: ^3.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  sunmi_printer_plus: ^4.1.0
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^4.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/lakasir.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/onboards/

fonts:
  - family: SourceSans
    fonts:
      - asset: fonts/SourceSans3-BlackItalic.ttf
      - asset: fonts/SourceSans3-BoldItalic.ttf
      - asset: fonts/SourceSans3-ExtraBoldItalic.ttf
      - asset: fonts/SourceSans3-ExtraLightItalic.ttf
      - asset: fonts/SourceSans3-Italic.ttf
      - asset: fonts/SourceSans3-LightItalic.ttf
      - asset: fonts/SourceSans3-MediumItalic.ttf
      - asset: fonts/SourceSans3-SemiBoldItalic.ttf
        style: italic
      - asset: fonts/SourceSans3-Black.ttf
      - asset: fonts/SourceSans3-Bold.ttf
      - asset: fonts/SourceSans3-ExtraBold.ttf
      - asset: fonts/SourceSans3-ExtraLight.ttf
      - asset: fonts/SourceSans3-Regular.ttf
      - asset: fonts/SourceSans3-Light.ttf
      - asset: fonts/SourceSans3-Medium.ttf
      - asset: fonts/SourceSans3-SemiBold.ttf
        style: normal
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
        style: normal

